name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome! Thank you for submitting an issue, the team will look into it soon."
        pr-message: "Thank you for your first pull request! Our team will review it soon. We appreciate your contribution to the project!"
